// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWH4xZAIEEOllNthiHh1HaGvaKqNgTqyo',
    appId: '1:909898289978:web:5f841e231c036732763603',
    messagingSenderId: '909898289978',
    projectId: 'fir-connect-new-6b408',
    authDomain: 'fir-connect-new-6b408.firebaseapp.com',
    storageBucket: 'fir-connect-new-6b408.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlgprmP1T_GxqZOUU-BNJ8VFPvitDakUs',
    appId: '1:909898289978:android:80b9e13f384317ad763603',
    messagingSenderId: '909898289978',
    projectId: 'fir-connect-new-6b408',
    storageBucket: 'fir-connect-new-6b408.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC00BTGR0m9lLv2M9NChTZPLf7dsDF2xH0',
    appId: '1:909898289978:ios:7eef28c81d067bcb763603',
    messagingSenderId: '909898289978',
    projectId: 'fir-connect-new-6b408',
    storageBucket: 'fir-connect-new-6b408.appspot.com',
    iosBundleId: 'com.example.mongodbFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC00BTGR0m9lLv2M9NChTZPLf7dsDF2xH0',
    appId: '1:909898289978:ios:7eef28c81d067bcb763603',
    messagingSenderId: '909898289978',
    projectId: 'fir-connect-new-6b408',
    storageBucket: 'fir-connect-new-6b408.appspot.com',
    iosBundleId: 'com.example.mongodbFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWH4xZAIEEOllNthiHh1HaGvaKqNgTqyo',
    appId: '1:909898289978:web:291eab522538a7ab763603',
    messagingSenderId: '909898289978',
    projectId: 'fir-connect-new-6b408',
    authDomain: 'fir-connect-new-6b408.firebaseapp.com',
    storageBucket: 'fir-connect-new-6b408.appspot.com',
  );
}
